build issues

diff --git a/.github/workflows/gradle-publish.yml b/.github/workflows/gradle-publish.yml
--- a/.github/workflows/gradle-publish.yml
+++ b/.github/workflows/gradle-publish.yml
@@ -10,6 +10,8 @@ name: Gradle Package
 env:
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
+  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
 
 on:
   push:
@@ -47,12 +49,17 @@ jobs:
       - name: Read Current Version
         id: version
         run: |
-          CURRENT_VERSION=$(grep "version=" gradle.properties | cut -d'=' -f2)
-          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
-          echo "Current version: $CURRENT_VERSION"
+          if [ -f "gradle.properties" ]; then
+            CURRENT_VERSION=$(grep "version=" gradle.properties | cut -d'=' -f2)
+            echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
+            echo "Current version: $CURRENT_VERSION"
+          else
+            echo "Error: gradle.properties not found!"
+            exit 1
+          fi
 
       - name: Determine Release Version (if master)
-        if: github.ref == 'refs/heads/master'
+        if: github.ref == 'refs/heads/master' || github.event_name == 'release'
         run: |
           RELEASE_VERSION=$(echo "${{ env.CURRENT_VERSION }}" | sed 's/-SNAPSHOT//')
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
@@ -66,26 +73,26 @@ jobs:
 
       - name: Publish Package
         run: |
-          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
+          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.event_name }}" == "release" ]]; then
             ./gradlew publish -Pversion=${{ env.RELEASE_VERSION }}
           else
             ./gradlew publish
           fi
 
       - name: Create Git Tag (if master)
-        if: github.ref == 'refs/heads/master'
+        if: github.ref == 'refs/heads/master' || github.event_name == 'release'
         run: |
-          git config --global user.name "github-actions"
-          git config --global user.email "actions@github.com"
-          git tag -a "v${{ env.RELEASE_VERSION }}" -m "Release version ${{ env.RELEASE_VERSION }}"
-          git push origin "v${{ env.RELEASE_VERSION }}"
+            git config --global user.name "github-actions"
+            git config --global user.email "actions@github.com"
+            git tag -a "v${{ env.RELEASE_VERSION }}" -m "Release version ${{ env.RELEASE_VERSION }}"
+            git push origin "v${{ env.RELEASE_VERSION }}"
 
       - name: Bump Version to Next Snapshot (if master)
         if: github.ref == 'refs/heads/master'
         run: |
-          NEW_VERSION=$(echo "${{ env.RELEASE_VERSION }}" | awk -F. '{$NF++; print}' OFS=.)
-          echo "version=$NEW_VERSION-SNAPSHOT" > gradle.properties
-          git config --global user.name "github-actions"
-          git config --global user.email "actions@github.com"
-          git commit -am "Bump version to $NEW_VERSION-SNAPSHOT"
-          git push origin master
+            NEW_VERSION=$(echo "${{ env.RELEASE_VERSION }}" | awk -F. '{$NF++; print}' OFS=.)
+            echo "version=$NEW_VERSION-SNAPSHOT" > gradle.properties
+            git config --global user.name "github-actions"
+            git config --global user.email "actions@github.com"
+            git commit -am "Bump version to $NEW_VERSION-SNAPSHOT"
+            git push origin master
